apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{.Values.image}}:{{.Values.imageTag}}"
        volumeMounts:
        - name: sitemaps
          mountPath: /usr/share/nginx/html/sitemaps
        ports: 
        - containerPort: 80
      volumes:
      - name: sitemaps
        azureFile:
          secretName: azure-files
          shareName: sitemaps
          readOnly: true